### ISSUE TITLE
data binding using managed bean to remote data

### ISSUE THREAD

**Issue by dataSQL** [chuck-durst/pit-scheduler#5]
Hello, has anyone accomplished connectivity with the most wonderful Pit-Scheduler to a remote data source using a manged bean?

Any suggestions greatly appreciated.

Jon

for example to connect to a regular html table 
[http://35.164.222.200/](url)

```

<h:body>
	<h:dataTable width="100%" value="#{queryBean.getDataList()}" var="u"
		border="1">

		<h:column>
			<f:facet name="header">Number</f:facet>
			#{u.caseno}
		</h:column>

	</h:dataTable>
</h:body>	
```

**Comment by dataSQL** [comment]
Hello, when I am able to serialize my bean to a JSON string, are there any instructions / directions on using your wonderful pit-scheduler to data bind with a JSON URL or ?

jsf managed bean accessing MySQL remote database - how to create JSON array to feed

http://stackoverflow.com/questions/41142802/jsf-managed-bean-accessing-mysql-remote-database-how-to-create-json-array-to-f

Any suggestions greatly appreciated.

Jon

**Comment by chuck-durst** [comment]
Hi Jon, I'm not sure to have correctly understand your question. However, if what you are trying to do is getting a JSON from an url,  you should try to use the getJson() function from jQuery:
[http://api.jquery.com/jQuery.getJSON/](url)

Theselinks may also help you:
[https://www.w3.org/TR/cors/](url)
[https://en.wikipedia.org/wiki/JSONP](url)

I hope that helps,

Chuck

**Comment by dataSQL** [comment]
Hello,
Still loving the music...
Thank you for your reply.

I am coding POJO to JSON string right now (with Jackson), and need to know what your wonderful schedule calendar requires for data binding.

**Comment by dataSQL** [comment]
the data is remote MySQL on AWS and is pulled into a xhtml file using a manged connection bean.

Since your component cannot use a direct connection, I have to convert to a JSON string to enable the data to pass to your scheduling data fields.

**Comment by dataSQL** [comment]
Please, what data binding is needed to pass data to your scheduling component?

**Comment by chuck-durst** [comment]
Have you take a look at the [documentation](http://chuck-engine.fr/demos/pit-scheduler/demo/views/options.html) ? As you said, there is no way to make a direct connection and the only way to pass data into the scheduler is mentioned into the doc. You have to set all your data when declaring the scheduler, and you can get it back with the events methods like onChange().

**Comment by dataSQL** [comment]
Excellent!  Thank you.
