### ISSUE TITLE
[RFC] depreceated momentjs / npm installation instructions

### ISSUE THREAD

**Issue by malikbenkirane** [chuck-durst/pit-scheduler#7]
Hello,

1. Refereeing to npm install output, momentjs is a depreceated dependency ([code here](https://github.com/chuck-durst/pit-scheduler/blob/697016573494db8627d97fb7c744b316fcd978ef/package.json#L9))
2. On top of what, instructions should be changed with npm installation (many paths do not match)

# npm instructions

I'm still issuing some difficulties to run this package, here are modifications I did :

```html
  <head>
    <!-- ... -->
    <link  rel="stylesheet" type="text/css" href="node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link  rel="stylesheet" type="text/css" href="node_modules/bootstrap-datetimepicker/src/less/bootstrap-datetimepicker.less">
    <link  rel="stylesheet" type="text/css" href="node_modules/pit-scheduler/dist/css/pitscheduler.min.css">

    <script src="node_modules/jquery/dist/jquery.min.js"></script>
    <script src="node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="node_modules/momentjs/build/moment.min.js"></script>
    <script src="node_modules/bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js"></script>
    <script src="node_modules/pit-scheduler/dist/js/pitscheduler.min.js"></script>
    <!-- ... -->
  </head>
```
# issues with a minimal example

Here is one issue i get (here using non minified pitscheduler.js for clarity) :

```
jQuery.Deferred exception: moment is not defined ReferenceError: moment is not defined
	at at r.fn.init.$.fn.pitScheduler (.../pitscheduler.js:122:26)
	at HTMLDocument.<anonymous> (.../calendar.js)
```

This is when trying to test a minimal example showed on ['installing' page](https://chuck-engine.fr/demos/pit-scheduler/demo/views/installing.html) :

```Javascript
$(document).ready(function() {
  $("#pit-scheduler").pitScheduler();
});
```

**Comment by chuck-durst** [comment]
Hi,

Sorry but this is a project I've made a long time ago now and I won't process any issue anymore. You'll have to find a solution on your own. I'll add a deprecated mention to the project name. 

Hope you'll find a way to fix your issue

**Comment by ssmersin** [comment]
Hi again Sir,
I am continuing my project and today I checked again the .js and I found the solution. Thanks anyway... Nice code..

Android için Outlook<https://aka.ms/ghei36> uygulamasını edinin

________________________________

**Comment by ssmersin** [comment]
Hi again,
I finally learn how to add my project. Itis not completed but I think enough to be used for others. 
I have a question. If you can help me I will be appriciated. My project is working on my desktop. But when I download from GitHub It's not working. What's changing when I upload? And If you can check my project I will be very happy. Because It is a version of yours you know.
